services:
  - type: web
    name: live-translate
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: PORT
        value: 10000

    preBuild:
      commands:
        - git submodule update --init --recursive
        - apt-get update && apt-get install -y ffmpeg

    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
