build:
  pythonVersion: 3.10
  command: |
    apt-get update && \
    apt-get install -y ffmpeg && \
    pip install --no-cache-dir -r requirements.txt

preBuild:
  commands:
    - git submodule update --init --recursive

start: python web_server.py
